### ISSUE TITLE
Initial setup and configurations

### ISSUE THREAD

**Issue by noamoss** [noamoss/similarity-hub#2]
Heroku Postgresql

**Comment by ordavidil** [comment]
- [ ] Create a new account in Heroku
- [ ] Create a wiki page with Heroku's information (links, credentials, etc.)
- [ ] Infrastructure code (decoupled)
- [ ] Use containers (https://kubernetes.io / https://www.docker.com)
- [ ] Deploy script

___
- [ ] Continuous Integration (see #9)

**Comment by ordavidil** [comment]
### Stack
- Flask
- postgreSQL
- Vue.Js

**Comment by noamoss** [comment]
I am taking over the Flask+Postgresql part [link](https://www.askpython.com/python-modules/flask/flask-postgresql)

**Comment by noamoss** [comment]
@ordavidil installed Herolu postgresql addon, see [here](https://data.heroku.com/datastores/f0442141-68da-40fb-a4f1-15eb8f91286b#administration) the DB credentials

**Comment by noamoss** [comment]
@ordavidil please see the updated readme, and let me know if were able to clone the repo and follow the instructions correctly. 
I already implemented (but did not finish checking) an initial version of the flask-sqlalchemy part on https://github.com/noamoss/similiarity-hub/pull/11, based on these definitions. I will update when ready for review.
